spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/accounts
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      accounts-customer: accounts.customers.change
    consumer:
      group-id: accounts
      auto-offset-reset: earliest
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: DEBUG
---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://mongo:27017/accounts
  kafka:
    bootstrap-servers: kafka:9092
logging:
  level:
    root: INFO